apiVersion: v1
kind: Namespace
metadata:
  name: scloud-gateway
  labels:
    name: scloud-gateway
    kubernetes.io/metadata.name: scloud-gateway
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: 2scloud
