apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
  namespace: scloud-observability
  labels:
    app: tempo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
