apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimir-data
  namespace: scloud-observability
  labels:
    app: mimir
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 6Gi
