apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-operator-binding
  namespace: scloud-compute
subjects:
  - kind: ServiceAccount
    name: platform-operator
    namespace: scloud-compute
roleRef:
  kind: Role
  name: platform-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-readonly-binding
  namespace: scloud-compute
subjects:
  - kind: ServiceAccount
    name: platform-readonly
    namespace: scloud-compute
roleRef:
  kind: Role
  name: platform-readonly
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-runner-binding
  namespace: scloud-compute
subjects:
  - kind: ServiceAccount
    name: ci-runner
    namespace: scloud-compute
roleRef:
  kind: Role
  name: ci-runner
  apiGroup: rbac.authorization.k8s.io