apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-operator-binding
  namespace: scloud-compute
subjects:
- kind: User
  name: onihilist
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: platform-operator
  apiGroup: rbac.authorization.k8s.io
