# ------------------------------------------------------------
# Platform Service Accounts
# ------------------------------------------------------------
# These ServiceAccounts define technical identities used by
# workloads and automation components within the platform namespace.
#
# Each ServiceAccount has a dedicated purpose to follow the
# principle of least privilege and improve security, auditing,
# and workload isolation.
#
# Service Accounts Overview:
#
# 1) platform-operator-sa
#    - Main platform automation identity
#    - Used by controllers or internal automation tools
#    - Responsible for managing workloads lifecycle:
#        * Create / update / delete deployments
#        * Manage pods, services, configmaps
#        * Access events for troubleshooting
#
# 2) platform-readonly-sa
#    - Observability and monitoring identity
#    - Provides read-only access to cluster resources
#    - Used by dashboards, monitoring tools, and debugging utilities
#    - Cannot modify or delete workloads
#
# 3) ci-runner-sa
#    - CI/CD automation identity
#    - Used by pipelines and deployment automation
#    - Responsible for deploying and updating platform workloads
#    - Allows controlled automated changes without granting full cluster admin access
#
# Security Notes:
# - Each ServiceAccount is bound to permissions via RBAC RoleBindings
# - ServiceAccounts are namespace-scoped and isolated
# - Workloads should use dedicated ServiceAccounts instead of the default one
# ------------------------------------------------------------

apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-operator
  namespace: scloud-compute
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-readonly
  namespace: scloud-compute
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-runner
  namespace: scloud-compute