apiVersion: v1
kind: LimitRange
metadata:
  name: gateway-limits
  namespace: scloud-gateway
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    default:
      cpu: "1000m"
      memory: "512Mi"
    min:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "2000m"
      memory: "1Gi"
  - type: Pod
    max:
      cpu: "4000m"
      memory: "2Gi"
