apiVersion: v1
kind: LimitRange
metadata:
  name: observability-limits
  namespace: scloud-observability
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      default:
        cpu: "1000m"
        memory: "1Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
      max:
        cpu: "4000m"
        memory: "8Gi"

    - type: Pod
      max:
        cpu: "4000m"
        memory: "8Gi"
      min:
        cpu: "100m"
        memory: "128Mi"

    - type: PersistentVolumeClaim
      defaultRequest:
        storage: "10Gi"
      default:
        storage: "20Gi"
      min:
        storage: "1Gi"
      max:
        storage: "50Gi"
